use_frameworks!

platform :ios, '8.0'

target 'JNCustomTool_Example' do
  pod 'JNCustomTool', :path => '../'

  target 'JNCustomTool_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
